"""
BU YERDA SIZGA KERAKLI BO'LADIGAN TOKEN VA SHUNGA O'XSHAGAN MA'LUMOTLAR SAQLANADI
"""
from settings import *
TOKEN = TELEGRAM_TOKEN
PROVIDER_TOKEN = "Pul o'tkazmalari uchun bo'lgan TOKEN buni ham botfatherdan olsa bo'ladi, test versiyasini"
ADMINS = '''Adminlarni saqlash uchun o'zgaruvchi, listdaham saqlasa bo'ladi'''

DB_NAME = '''POSTGRES ISHLATGANDA BAZANI ISMINI SAQLASH UCHUN'''
DB_HOST = '''POSTGRES ISHLATGANDA BAZANI HOSTINI SAQLASH UCHUN'''
DB_PASSWORD = '''POSTGRES ISHLATGANDA BAZANI PAROLINI SAQLASH UCHUN'''
DB_PORT = '''POSTGRES ISHLATGANDA BAZANI PORTINI SAQLASH UCHUN'''
DB_USER = '''POSTGRES ISHLATGANDA BAZANI FOYDALANUVCHISINING ISMINI SAQLASH UCHUN'''


